version: '3.8'

services:
  postgres_nlw:
    container_name: postgres_nlw
    image: postgres:latest
    environment:
      POSTGRES_DB: pg_nlw
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"